import {AminoAcidEnum} from "./AminoAcidEnum";

const dnaCodonMapping = {
    "GCT": AminoAcidEnum.ALANINE,
    "GCC": AminoAcidEnum.ALANINE,
    "GCA": AminoAcidEnum.ALANINE,
    "GCG": AminoAcidEnum.ALANINE,
    "CGT": AminoAcidEnum.ARGININE,
    "CGC": AminoAcidEnum.ARGININE,
    "CGA": AminoAcidEnum.ARGININE,
    "CGG": AminoAcidEnum.ARGININE,
    "AGA": AminoAcidEnum.ARGININE,
    "AGG": AminoAcidEnum.ARGININE,
    "AAC": AminoAcidEnum.ASPARAGINE,
    "AAT": AminoAcidEnum.ASPARAGINE,
    "GAT": AminoAcidEnum.ASPARTIC_ACID,
    "GAC": AminoAcidEnum.ASPARTIC_ACID,
    "TGT": AminoAcidEnum.CYSTEINE,
    "TGC": AminoAcidEnum.CYSTEINE,
    "CAA": AminoAcidEnum.GLUTAMINE,
    "CAG": AminoAcidEnum.GLUTAMINE,
    "GAA": AminoAcidEnum.GLUTAMIC_ACID,
    "GAG": AminoAcidEnum.GLUTAMIC_ACID,
    "GGT": AminoAcidEnum.GLYCINE,
    "GGC": AminoAcidEnum.GLYCINE,
    "GGA": AminoAcidEnum.GLYCINE,
    "GGG": AminoAcidEnum.GLYCINE,
    "CAT": AminoAcidEnum.HISTIDINE,
    "CAC": AminoAcidEnum.HISTIDINE,
    "ATT": AminoAcidEnum.ISOLEUCINE,
    "ATC": AminoAcidEnum.ISOLEUCINE,
    "ATA": AminoAcidEnum.ISOLEUCINE,
    "CTT": AminoAcidEnum.LEUCINE,
    "CTC": AminoAcidEnum.LEUCINE,
    "CTA": AminoAcidEnum.LEUCINE,
    "CTG": AminoAcidEnum.LEUCINE,
    "TTA": AminoAcidEnum.LEUCINE,
    "TTG": AminoAcidEnum.LEUCINE,
    "AAA": AminoAcidEnum.LYSINE,
    "AAG": AminoAcidEnum.LYSINE,
    "ATG": AminoAcidEnum.METHIONINE,
    "TTT": AminoAcidEnum.PHENYLALANINE,
    "TTC": AminoAcidEnum.PHENYLALANINE,
    "CCT": AminoAcidEnum.PROLINE,
    "CCC": AminoAcidEnum.PROLINE,
    "CCA": AminoAcidEnum.PROLINE,
    "CCG": AminoAcidEnum.PROLINE,
    "TCT": AminoAcidEnum.SERINE,
    "TCC": AminoAcidEnum.SERINE,
    "TCA": AminoAcidEnum.SERINE,
    "TCG": AminoAcidEnum.SERINE,
    "AGT": AminoAcidEnum.SERINE,
    "AGC": AminoAcidEnum.SERINE,
    "ACT": AminoAcidEnum.THREONINE,
    "ACC": AminoAcidEnum.THREONINE,
    "ACA": AminoAcidEnum.THREONINE,
    "ACG": AminoAcidEnum.THREONINE,
    "TGG": AminoAcidEnum.TRYPTOPHAN,
    "TAT": AminoAcidEnum.TYROSINE,
    "TAC": AminoAcidEnum.TYROSINE,
    "GTT": AminoAcidEnum.VALINE,
    "GTC": AminoAcidEnum.VALINE,
    "GTA": AminoAcidEnum.VALINE,
    "GTG": AminoAcidEnum.VALINE,
    "TAA": AminoAcidEnum.STOP,
    "TGA": AminoAcidEnum.STOP,
    "TAG": AminoAcidEnum.STOP
}

const dnaMap = new Map(Object.entries(dnaCodonMapping));

export default dnaMap;